# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-04 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrange_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('set', models.IntegerField(default=0)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('usedTime', models.FloatField(default=0.0)),
                ('wrong_ques', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recom_guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.IntegerField(default=0)),
                ('sentence', models.CharField(max_length=60, null=True)),
                ('count', models.IntegerField(default=0)),
                ('value', models.FloatField(default=0.0)),
                ('epsilon', models.FloatField(default=0.3)),
                ('gamma', models.FloatField(default=0.3)),
                ('weight', models.FloatField(default=1.0)),
                ('temperature', models.FloatField(default=0.3)),
                ('alpha', models.FloatField(default=0.5)),
                ('current_arm', models.IntegerField(default=0)),
                ('next_update', models.IntegerField(default=0)),
                ('r', models.IntegerField(default=0)),
            ],
        ),
    ]
