# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-09 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20180605_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='wrong_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('question_id', models.IntegerField(default=0)),
                ('wrong_choice', models.IntegerField(default=0)),
                ('guide', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
