# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-02 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_arrange_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrange_set',
            name='usedTime',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='arrange_set',
            name='wrong_ques',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
