# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-04 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setId', models.IntegerField()),
                ('setDes', models.CharField(max_length=200, null=True)),
                ('questions', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
