# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-29 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeSet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='setDes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
