# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-04 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answer', models.CharField(max_length=30, null=True)),
                ('wrong_answer', models.CharField(max_length=30, null=True)),
                ('tips', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30, null=True)),
                ('imageA', models.ImageField(null=True, upload_to='image/%Y/%m/%d/')),
                ('DesA', models.CharField(max_length=30, null=True)),
                ('imageB', models.ImageField(null=True, upload_to='image/%Y/%m/%d/')),
                ('DesB', models.CharField(max_length=30, null=True)),
                ('imageC', models.ImageField(null=True, upload_to='image/%Y/%m/%d/')),
                ('DesC', models.CharField(max_length=30, null=True)),
                ('imageD', models.ImageField(null=True, upload_to='image/%Y/%m/%d/')),
                ('DesD', models.CharField(max_length=30, null=True)),
                ('voice', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
